### ISSUE TITLE
5.4.2  Ditruptor 代码有个小问题哈

### ISSUE THREAD

**Issue by bayern01kahn** [guanpengchn/java-concurrent-programming#1]
你好 感谢你分享的代码. 发现个小问题. Just FYI.

Main.java  里面.

for (long l = 0; true; l++) {
            bb.putLong(0, l);  <=(这里 应该是 l 不是 1 哈)
            System.out.println("Producer: 生产: add data "+l);
            producer.pushData(bb);
            Thread.sleep(10);
}

**Comment by guanpengchn** [comment]
感谢指出，我修改下

**Comment by guanpengchn** [comment]
已经修复
